# Generated by Django 3.0.3 on 2020-10-09 06:27

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20201009_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.JPG', upload_to=profiles.models.mainimage),
        ),
    ]
