# Generated by Django 3.0.3 on 2020-10-09 06:39

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20201009_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.JPG', upload_to=profiles.models.secondimage),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default='default.JPG', upload_to=profiles.models.thirdimage),
        ),
    ]
